(function(){
  const frame=document.getElementById('app');
  if(!frame)return;
  function install(){
    const d=frame.contentDocument,w=frame.contentWindow;
    if(!d||!w||!d.body||!w.ROSTERS||!w.state||!w.KEY)return false;
    if(d.getElementById('rosterDeleteUpgrade'))return true;
    const marker=d.createElement('div');marker.id='rosterDeleteUpgrade';marker.hidden=true;d.body.appendChild(marker);
    const style=d.createElement('style');style.textContent='.danger-mini{border:1px solid rgba(255,107,107,.55)!important;color:#ffd4d4!important;background:rgba(255,107,107,.08)!important}.student-manager{display:grid;gap:12px}.student-manager-head{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.student-manager-head input{min-width:220px}.student-manager-list{display:grid;gap:7px}.student-manager-row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:9px 10px;border:1px solid rgba(255,255,255,.12);border-radius:9px}.student-manager-title{font-family:"Segoe Print","Comic Sans MS",cursive;font-size:24px;margin:0}.student-count{color:var(--muted);font-size:12px}@media(max-width:650px){.student-manager-head>*{width:100%}.student-manager-row{align-items:flex-start}}';d.head.appendChild(style);
    const main=d.querySelector('main.main');
    const sec=d.createElement('section');sec.id='studentManagerView';sec.className='hidden';sec.innerHTML='<div class="panel student-manager"><div><h2 class="student-manager-title">Manage Students</h2><div class="history-help">Add late registrations or remove students who are no longer in a class.</div></div><div class="student-manager-head"><button class="secondary" id="studentManagerBack">← Back to Dashboard</button><select id="studentManagerClass"></select><input id="newStudentName" placeholder="Student display name"><button class="primary" id="addStudentNow">＋ Add Student</button></div><div class="student-count" id="studentManagerCount"></div><div class="student-manager-list" id="studentManagerList"></div></div>';main.appendChild(sec);
    const nav=d.querySelector('.nav'),reset=d.getElementById('resetBtn');if(nav){const b=d.createElement('button');b.id='studentManagerNav';b.textContent='➕ Manage Students';nav.insertBefore(b,reset)}
    const sel=d.getElementById('studentManagerClass'),name=d.getElementById('newStudentName'),list=d.getElementById('studentManagerList');sel.innerHTML=Object.keys(w.ROSTERS).map(c=>'<option>'+w.esc(c)+'</option>').join('');sel.value=w.currentClass||Object.keys(w.ROSTERS)[0];
    function save(){localStorage.setItem(w.KEY,JSON.stringify(w.state));if(typeof w.renderAll==='function')w.renderAll()}
    function show(id){if(typeof w.teacherShowOnly==='function')w.teacherShowOnly(id);else ['dashboardView','studentManagerView'].forEach(x=>d.getElementById(x)?.classList.toggle('hidden',x!==id));if(id==='studentManagerView'){d.getElementById('studentManagerView').classList.remove('hidden');d.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));d.getElementById('studentManagerNav')?.classList.add('active')}}
    function render(){const cls=sel.value,names=w.ROSTERS[cls]||[];d.getElementById('studentManagerCount').textContent=names.length+' students in '+cls;list.innerHTML=names.map(n=>'<div class="student-manager-row"><strong>'+w.esc(n)+'</strong><button class="secondary danger-mini" data-delete-student="'+w.esc(n)+'" title="Delete student">🗑 Delete</button></div>').join('');list.querySelectorAll('[data-delete-student]').forEach(b=>b.onclick=()=>removeStudent(b.dataset.deleteStudent))}
    function removeStudent(student){const cls=sel.value;if(!confirm('Are you sure you want to delete '+student+' from '+cls+'? This removes the student and their locally stored attendance, notes and participation data.'))return;const i=w.ROSTERS[cls].indexOf(student);if(i>=0)w.ROSTERS[cls].splice(i,1);delete w.state.students?.[cls]?.[student];try{const ak='neil_teacher_assignments_v1',ad=JSON.parse(localStorage.getItem(ak));(ad?.classes?.[cls]?.assignments||[]).forEach(a=>{if(a.students)delete a.students[student]});localStorage.setItem(ak,JSON.stringify(ad))}catch(e){}save();render();window.dispatchEvent(new Event('teacherRosterChanged'))}
    function addStudent(){const cls=sel.value,student=name.value.trim();if(!student){alert('Enter the student name.');return}if(w.ROSTERS[cls].some(n=>n.toLowerCase()===student.toLowerCase())){alert('That student is already in this class.');return}w.ROSTERS[cls].push(student);w.state.students[cls][student]={attendance:[],participation:null,notes:[],missing:[]};save();name.value='';render();window.dispatchEvent(new Event('teacherRosterChanged'))}
    d.getElementById('addStudentNow').onclick=addStudent;name.addEventListener('keydown',e=>{if(e.key==='Enter')addStudent()});sel.onchange=render;d.getElementById('studentManagerBack').onclick=()=>show('dashboardView');d.getElementById('studentManagerNav').onclick=()=>{sel.value=w.currentClass||sel.value;show('studentManagerView');render()};
    const cards=d.getElementById('classCards');if(cards){const observer=new MutationObserver(()=>{d.querySelectorAll('.class-card').forEach(card=>{if(card.querySelector('.manage-students-btn'))return;const actions=card.querySelector('.card-actions');if(actions){const b=d.createElement('button');b.className='mini-btn manage-students-btn';b.textContent='＋ Students';b.onclick=e=>{e.preventDefault();e.stopPropagation();sel.value=card.dataset.class;show('studentManagerView');render()};actions.appendChild(b)}})});observer.observe(cards,{childList:true,subtree:true});observer.takeRecords();setTimeout(()=>{d.querySelectorAll('.class-card').forEach(card=>{if(!card.querySelector('.manage-students-btn')){const actions=card.querySelector('.card-actions');if(actions){const b=d.createElement('button');b.className='mini-btn manage-students-btn';b.textContent='＋ Students';b.onclick=e=>{e.preventDefault();e.stopPropagation();sel.value=card.dataset.class;show('studentManagerView');render()};actions.appendChild(b)}}})},300)}
    function addAssignmentTrash(){const al=d.getElementById('assignmentList');if(!al)return;const decorate=()=>{al.querySelectorAll('.assignment-card').forEach(card=>{if(card.querySelector('.delete-assignment-btn'))return;const open=card.querySelector('[data-open-assignment]'),archive=card.querySelector('[data-archive-assignment]'),id=open?.dataset.openAssignment||archive?.dataset.archiveAssignment;if(!id)return;const b=d.createElement('button');b.className='secondary danger-mini delete-assignment-btn';b.textContent='🗑 Delete';b.dataset.deleteAssignment=id;b.onclick=()=>{const title=card.querySelector('h4')?.textContent?.replace('(archived)','').trim()||'this assignment';if(!confirm('Are you sure you want to permanently delete “'+title+'”? All submission checks and marks for this assignment will also be deleted.'))return;try{const key='neil_teacher_assignments_v1',data=JSON.parse(localStorage.getItem(key));const cls=d.querySelector('.assignment-tab.active')?.dataset.assignmentClass||w.currentClass;const arr=data?.classes?.[cls]?.assignments;if(Array.isArray(arr)){const i=arr.findIndex(a=>a.id===id);if(i>=0)arr.splice(i,1);localStorage.setItem(key,JSON.stringify(data));location.reload()}}catch(e){alert('I could not delete that assignment. Please refresh and try again.')}};(card.querySelector('.assignment-actions')||card).appendChild(b)})};new MutationObserver(decorate).observe(al,{childList:true,subtree:true});decorate()}
    addAssignmentTrash();render();return true;
  }
  let tries=0;const timer=setInterval(()=>{if(install()||++tries>30)clearInterval(timer)},250);frame.addEventListener('load',()=>{tries=0});
})();