(function(){
  const frame=document.getElementById('app');
  if(!frame)return;
  function isoDate(){const d=new Date(),l=new Date(d.getTime()-d.getTimezoneOffset()*60000);return l.toISOString().slice(0,10)}
  function assignmentData(w){try{return JSON.parse(w.localStorage.getItem('neil_teacher_assignments_v1'))||{}}catch(e){return{}}}
  function buildExport(w){return{format:'teacher-command-centre-winston-export',version:3,exportedAt:new Date().toISOString(),teacherApp:{currentClass:w.currentClass,studentData:w.state},assignmentTracker:assignmentData(w)}}
  function status(d,msg){let b=d.getElementById('winstonSendStatus');if(!b){b=d.createElement('div');b.id='winstonSendStatus';d.getElementById('downloadWinstonJson')?.insertAdjacentElement('afterend',b)}if(b){b.textContent=msg;b.style.cssText='margin-top:10px;padding:10px 12px;border-radius:8px;font-size:13px;line-height:1.4;border:1px solid rgba(99,214,139,.45);background:rgba(99,214,139,.08)'}}
  async function send(d,w,btn){const payload=JSON.stringify(buildExport(w),null,2);btn.disabled=true;btn.textContent='Preparing for Winston…';try{await navigator.clipboard.writeText(payload);btn.textContent='✓ Copied — paste in ChatGPT';status(d,'Ready. Return to this ChatGPT conversation, click the message box, paste (Ctrl+V), and send. Winston will reply “Yeah I got it.”')}catch(e){const ta=d.createElement('textarea');ta.value=payload;ta.style.position='fixed';ta.style.left='-9999px';d.body.appendChild(ta);ta.select();let ok=false;try{ok=d.execCommand('copy')}catch(_){}ta.remove();if(ok){btn.textContent='✓ Copied — paste in ChatGPT';status(d,'Ready. Return to this ChatGPT conversation, paste (Ctrl+V), and send. Winston will reply “Yeah I got it.”')}else{btn.textContent='Copy failed';status(d,'This browser blocked clipboard access. Open this dashboard in Chrome or Edge and try Send to Winston again.')}}finally{setTimeout(()=>{btn.disabled=false},500)}}
  function patch(){const d=frame.contentDocument,w=frame.contentWindow;if(!d||!w||!w.state)return false;const old=d.getElementById('downloadWinstonJson');if(!old)return false;if(old.dataset.winstonDirectV3==='1')return true;
    // Clone the button to remove the original download onclick installed by notes-export.js.
    const btn=old.cloneNode(true);btn.dataset.winstonDirectV3='1';btn.id='downloadWinstonJson';btn.textContent='↗ Send to Winston';btn.title='Copy current teacher data for pasting directly into this ChatGPT conversation';old.replaceWith(btn);
    const card=btn.closest('.export-card');if(card){const h=card.querySelector('h3');if(h)h.textContent='Send to Winston';const p=card.querySelector('p');if(p)p.textContent='Copies your current attendance, participation, notes, missing work, and assignment data in one tap. Then return to your ChatGPT conversation, paste, and send — no downloaded JSON file needed.'}
    btn.onclick=e=>{e.preventDefault();e.stopPropagation();send(d,w,btn)};return true}
  frame.addEventListener('load',()=>setTimeout(patch,1400));let tries=0;const timer=setInterval(()=>{patch();if(++tries>240)clearInterval(timer)},250);
})();